import { RolePermissionsMatrix } from "./types";

/**
 * Default Factory Permissions Matrix for Star Mould ERP:
 * 0: Admin (100% full access, immutable safety lock)
 * 1: Manager (commercial, procurement, movements, vendors, expenses, reports)
 * 2: Supervisor (floor operations, scanning, printing, challan, dispatch, inward, QC, worklogs)
 * 3: Designer (scanning, subplates, sample/rework, worklogs)
 * 4: Worker (worklogs, personal tasks, mould view)
 */
export const DEFAULT_ROLE_PERMISSIONS: RolePermissionsMatrix = {
  // 0: ADMIN (ALL PERMISSIONS ENABLED)
  0: {
    nav_dashboard: true,
    nav_customer_creator: true,
    nav_vendor_transport: true,
    nav_subplate: true,
    nav_scanning: true,
    nav_printing: true,
    nav_purchase: true,
    nav_purchase_inward: true,
    nav_challan: true,
    nav_dispatch: true,
    nav_inward: true,
    nav_work: true,
    nav_sample: true,
    nav_expense: true,
    nav_gram: true,
    nav_user_mgmt: true,
    nav_settings: true,
    nav_reports: true,
    nav_export: true,
    action_create_customer: true,
    action_create_vendor: true,
    action_create_scanning_project: true,
    action_approve_qc: true,
    action_create_purchase: true,
    action_create_challan_dispatch: true,
    action_manage_expenses: true,
    action_manage_users: true,
    financial_view_amounts: true,
    financial_export_csv: true,
    financial_soft_delete: true,
  },

  // 1: MANAGER
  1: {
    nav_dashboard: true,
    nav_customer_creator: false, // Customer creation restricted to Admin by default
    nav_vendor_transport: true,
    nav_subplate: false,
    nav_scanning: false,
    nav_printing: false,
    nav_purchase: true,
    nav_purchase_inward: true,
    nav_challan: true,
    nav_dispatch: true,
    nav_inward: true,
    nav_work: false,
    nav_sample: false,
    nav_expense: true,
    nav_gram: true,
    nav_user_mgmt: false,
    nav_reports: true,
    nav_export: true,
    action_create_customer: false,
    action_create_vendor: true,
    action_create_scanning_project: false,
    action_approve_qc: false,
    action_create_purchase: true,
    action_create_challan_dispatch: true,
    action_manage_expenses: true,
    action_manage_users: false,
    financial_view_amounts: true,
    financial_export_csv: true,
    financial_soft_delete: false,
  },

  // 2: SUPERVISOR
  2: {
    nav_dashboard: true,
    nav_customer_creator: false,
    nav_vendor_transport: false,
    nav_subplate: true,
    nav_scanning: true,
    nav_printing: true,
    nav_purchase: false,
    nav_purchase_inward: false,
    nav_challan: true,
    nav_dispatch: true,
    nav_inward: true,
    nav_work: true,
    nav_sample: true,
    nav_expense: false,
    nav_gram: false,
    nav_user_mgmt: false,
    nav_reports: true,
    nav_export: false,
    action_create_customer: false,
    action_create_vendor: false,
    action_create_scanning_project: true,
    action_approve_qc: true,
    action_create_purchase: false,
    action_create_challan_dispatch: true,
    action_manage_expenses: false,
    action_manage_users: false,
    financial_view_amounts: false,
    financial_export_csv: false,
    financial_soft_delete: false,
  },

  // 3: DESIGNER
  3: {
    nav_dashboard: true,
    nav_customer_creator: false,
    nav_vendor_transport: false,
    nav_subplate: true,
    nav_scanning: true,
    nav_printing: false,
    nav_purchase: false,
    nav_purchase_inward: false,
    nav_challan: false,
    nav_dispatch: false,
    nav_inward: false,
    nav_work: true,
    nav_sample: true,
    nav_expense: false,
    nav_gram: false,
    nav_user_mgmt: false,
    nav_reports: false,
    nav_export: false,
    action_create_customer: false,
    action_create_vendor: false,
    action_create_scanning_project: true,
    action_approve_qc: false,
    action_create_purchase: false,
    action_create_challan_dispatch: false,
    action_manage_expenses: false,
    action_manage_users: false,
    financial_view_amounts: false,
    financial_export_csv: false,
    financial_soft_delete: false,
  },

  // 4: WORKER
  4: {
    nav_dashboard: true,
    nav_customer_creator: false,
    nav_vendor_transport: false,
    nav_subplate: false,
    nav_scanning: true,
    nav_printing: false,
    nav_purchase: false,
    nav_purchase_inward: false,
    nav_challan: false,
    nav_dispatch: false,
    nav_inward: false,
    nav_work: true,
    nav_sample: false,
    nav_expense: false,
    nav_gram: false,
    nav_user_mgmt: false,
    nav_reports: false,
    nav_export: false,
    action_create_customer: false,
    action_create_vendor: false,
    action_create_scanning_project: false,
    action_approve_qc: false,
    action_create_purchase: false,
    action_create_challan_dispatch: false,
    action_manage_expenses: false,
    action_manage_users: false,
    financial_view_amounts: false,
    financial_export_csv: false,
    financial_soft_delete: false,
  },
};

export const DEFAULT_ROLE_MENU_ORDERS: Record<number, string[]> = {
  0: [
    "nav_dashboard",
    "nav_customer_creator",
    "nav_vendor_transport",
    "nav_subplate",
    "nav_scanning",
    "nav_printing",
    "nav_purchase",
    "nav_purchase_inward",
    "nav_challan",
    "nav_dispatch",
    "nav_inward",
    "nav_work",
    "nav_sample",
    "nav_expense",
    "nav_gram",
    "nav_user_mgmt",
    "nav_settings",
    "nav_reports",
    "nav_export",
  ],
  1: [
    "nav_dashboard",
    "nav_vendor_transport",
    "nav_purchase",
    "nav_purchase_inward",
    "nav_challan",
    "nav_dispatch",
    "nav_inward",
    "nav_expense",
    "nav_gram",
    "nav_reports",
    "nav_export",
  ],
  2: [
    "nav_dashboard",
    "nav_subplate",
    "nav_scanning",
    "nav_printing",
    "nav_challan",
    "nav_dispatch",
    "nav_inward",
    "nav_work",
    "nav_sample",
    "nav_reports",
  ],
  3: [
    "nav_dashboard",
    "nav_subplate",
    "nav_scanning",
    "nav_work",
    "nav_sample",
  ],
  4: [
    "nav_dashboard",
    "nav_scanning",
    "nav_work",
  ],
};
